# POST http://localhost:5000/signup
# Content-Type: "application/json"

# {
#     "first_name": "Nur", 
#     "last_name": "Mazumder",
#     "email" : "dasa60196@gmail.com",
#     "user_password" : "another_passcode",
#     "major" : "computer science",
#     "date_of_birth" : "08/13/2002",
#     "pronouns" : "he/him",
#     "gender" : "male",
#     "degree_type" : "bachelor of science",
#     "college_year" : "4"
# }

# POST http://localhost:5000/signin
# Content-Type: "application/json"

# {
#     "email" : "dasa90196@gmail.com",
#     "password" : "another_passcode"
# }

# GET http://localhost:5000/rmp/summary/douglas 
# GET http://localhost:5000/rmp/get_professor_list
GET http://localhost:5000/ccny/courses/electrical engineering
